### ISSUE TITLE
JSProvider.ashx

### ISSUE THREAD

**Issue by Couchiman** [XrmServiceToolkit/XrmServiceToolkit#14]
Using last chrome version, the library is showing on console:

Refused to set unsafe header "Content-Length"

_common/JsProvider.ashx?ids=1759665639-1968334880-202661451-1547461133-1979…838-1501510414-867105739-1281389456-2050812538-512064351&ver=-715257483:20"

And

"The provided value 'msxml-document' is not a valid enum value of type XMLHttpRequestResponseType."

**Comment by ghost** [comment]
That is a general problem of Dynamics CRM and not a library specific. You will pretty much get that always, even if CRM makes own calls against the WebService.
