### ISSUE TITLE
Instructions for building from source?

### ISSUE THREAD

**Issue by claym** [XrmServiceToolkit/XrmServiceToolkit#2]
Are there any instructions for building from source? 

It seems the .min file is behind the full version. Is it best to just run it through a generic minifier and go?

**Comment by con-ssc** [comment]
For me it seems that both are 2.2.1, at least the version says so. In the min file there are only the credits not the changes, and the credits are a bit old.
You can also run the .js through an minifier, don't forget to switch off mangle if you do that though.
There is also a TypeScript branch if you are interested in that. That supports webpack for building.
If you need further assistance just contact me in the way you already did :)
If you have other issues just drop them in this section as well.
