### ISSUE TITLE
errorHandler fails because JSON.parse does not handle empty string in req.responseText

### ISSUE THREAD

**Issue by Zeek2** [XrmServiceToolkit/XrmServiceToolkit#5]
Hi, I have a problem with XrmServiceToolkit, is this the place to report it?

Essentially errorHandler fails when the webserver returns an error such as 12152 or 12019, as the JSON.parser cannot parse the empty string req.responseText. The debugger reports "Syntax Error".

As the XmlServiceToolkit error handler fails, nothing is returned to the caller, so our calling UI hangs waiting for a response that never comes.

If I replace the error string operations:
"Error : " +
 req.status + ": " +
 req.statusText + ": " +
 JSON.parse(req.responseText).error.message.value

...wIth a simple string (e.g. "Hacked error string") it works fine. The problem is the JSON.parse cannot handle empty string.

**Comment by Zeek2** [comment]
Image of debugger watch values, showing the empty strings returned by the (Microsoft IIS) webserver for error 12019  [ Ref. error values listed at: https://support.microsoft.com/en-us/kb/193625 ] which cause errorHandler to fail.

![xrmservicestoolkit](https://cloud.githubusercontent.com/assets/22198523/18542452/db53a334-7b22-11e6-9689-5021ac9c8a9b.jpg)

There are many ways in which this could be fixed.  One approach would be to wrap that line with an exception handler (note: the exception DOES NOT get passed back to our calling code - so exception handling there is not triggered).

e.g.

	var errorHandler = function (req) {
		///<summary>
		/// Private function return an Error object to the errorCallback
		///</summary>
		///<param name="req" type="XMLHttpRequest">
		/// The XMLHttpRequest response that returned an error.
		///</param>
		///<returns>Error</returns>
		try {
			return new Error("Error : " +
				req.status + ": " +
				req.statusText + ": " +
				JSON.parse(req.responseText).error.message.value);
		}
		catch (err) {
			// Error status codes: https://support.microsoft.com/en-us/kb/193625
			return new Error("Error : " +
				req.status + ": " +
				req.statusText + ": " +
				"Response text error could not be parsed (empty?). Webserver may have timed out before CRM responded.");
		}
	};

**Comment by con-ssc** [comment]
Yes this should be the place. I will look into it.

**Comment by Zeek2** [comment]
Hi, Did something change?

**Comment by con-ssc** [comment]
no I just used Zenhub :)
